<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pais = [
            ['codigo' => '9320', 'valor' => 'ANGUILA', 'status' => 'Desactivado'],
            ['codigo' => '9539', 'valor' => 'ISLAS TURCAS Y CAICOS', 'status' => 'Desactivado'],
            ['codigo' => '9565', 'valor' => 'LITUANIA', 'status' => 'Desactivado'],
            ['codigo' => '9905', 'valor' => 'DAKOTA DEL SUR (USA)', 'status' => 'Desactivado'],
            ['codigo' => '9999', 'valor' => 'No definido en migración', 'status' => 'Desactivado'],
            ['codigo' => '9303', 'valor' => 'AFGANISTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9306', 'valor' => 'ALBANIA', 'status' => 'Desactivado'],
            ['codigo' => '9309', 'valor' => 'ALEMANIA OCCID', 'status' => 'Desactivado'],
            ['codigo' => '9310', 'valor' => 'ALEMANIA ORIENT', 'status' => 'Desactivado'],
            ['codigo' => '9315', 'valor' => 'ALTO VOLTA', 'status' => 'Desactivado'],
            ['codigo' => '9317', 'valor' => 'ANDORRA', 'status' => 'Desactivado'],
            ['codigo' => '9318', 'valor' => 'ANGOLA', 'status' => 'Desactivado'],
            ['codigo' => '9319', 'valor' => 'ANTIG Y BARBUDA', 'status' => 'Desactivado'],
            ['codigo' => '9324', 'valor' => 'ARABIA SAUDITA', 'status' => 'Desactivado'],
            ['codigo' => '9327', 'valor' => 'ARGELIA', 'status' => 'Desactivado'],
            ['codigo' => '9330', 'valor' => 'ARGENTINA', 'status' => 'Desactivado'],
            ['codigo' => '9333', 'valor' => 'AUSTRALIA', 'status' => 'Desactivado'],
            ['codigo' => '9336', 'valor' => 'AUSTRIA', 'status' => 'Desactivado'],
            ['codigo' => '9339', 'valor' => 'BANGLADESH', 'status' => 'Desactivado'],
            ['codigo' => '9342', 'valor' => 'BAHRÉIN', 'status' => 'Desactivado'],
            ['codigo' => '9345', 'valor' => 'BARBADOS', 'status' => 'Desactivado'],
            ['codigo' => '9348', 'valor' => 'BÉLGICA', 'status' => 'Desactivado'],
            ['codigo' => '9349', 'valor' => 'BELICE', 'status' => 'Desactivado'],
            ['codigo' => '9350', 'valor' => 'BENÍN', 'status' => 'Desactivado'],
            ['codigo' => '9354', 'valor' => 'BIRMANIA', 'status' => 'Desactivado'],
            ['codigo' => '9357', 'valor' => 'BOLIVIA', 'status' => 'Desactivado'],
            ['codigo' => '9360', 'valor' => 'BOTSWANA', 'status' => 'Desactivado'],
            ['codigo' => '9363', 'valor' => 'BRASIL', 'status' => 'Desactivado'],
            ['codigo' => '9366', 'valor' => 'BRUNÉI', 'status' => 'Desactivado'],
            ['codigo' => '9372', 'valor' => 'BURUNDI', 'status' => 'Desactivado'],
            ['codigo' => '9374', 'valor' => 'BOPHUTHATSWANA', 'status' => 'Desactivado'],
            ['codigo' => '9375', 'valor' => 'BUTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9377', 'valor' => 'CABO VERDE', 'status' => 'Desactivado'],
            ['codigo' => '9378', 'valor' => 'CAMBOYA', 'status' => 'Desactivado'],
            ['codigo' => '9381', 'valor' => 'CAMERÚN', 'status' => 'Desactivado'],
            ['codigo' => '9384', 'valor' => 'CANADÁ', 'status' => 'Desactivado'],
            ['codigo' => '9387', 'valor' => 'CEILÁN', 'status' => 'Desactivado'],
            ['codigo' => '9390', 'valor' => 'CTRO AFRIC REP', 'status' => 'Desactivado'],
            ['codigo' => '9393', 'valor' => 'COLOMBIA', 'status' => 'Desactivado'],
            ['codigo' => '9394', 'valor' => 'COMORAS-ISLAS', 'status' => 'Desactivado'],
            ['codigo' => '9396', 'valor' => 'CONGO REP DEL', 'status' => 'Desactivado'],
            ['codigo' => '9399', 'valor' => 'CONGO REP DEMOC', 'status' => 'Desactivado'],
            ['codigo' => '9402', 'valor' => 'COREA NORTE', 'status' => 'Desactivado'],
            ['codigo' => '9405', 'valor' => 'COREA SUR', 'status' => 'Desactivado'],
            ['codigo' => '9408', 'valor' => 'COSTA DE MARFIL', 'status' => 'Desactivado'],
            ['codigo' => '9411', 'valor' => 'COSTA RICA', 'status' => 'Desactivado'],
            ['codigo' => '9414', 'valor' => 'CUBA', 'status' => 'Desactivado'],
            ['codigo' => '9417', 'valor' => 'CHAD', 'status' => 'Desactivado'],
            ['codigo' => '9420', 'valor' => 'CHECOSLOVAQUIA', 'status' => 'Desactivado'],
            ['codigo' => '9423', 'valor' => 'CHILE', 'status' => 'Desactivado'],
            ['codigo' => '9426', 'valor' => 'CHINA REP POPUL', 'status' => 'Desactivado'],
            ['codigo' => '9432', 'valor' => 'CHIPRE', 'status' => 'Desactivado'],
            ['codigo' => '9435', 'valor' => 'DAHOMEY', 'status' => 'Desactivado'],
            ['codigo' => '9438', 'valor' => 'DINAMARCA', 'status' => 'Desactivado'],
            ['codigo' => '9440', 'valor' => 'DOMINICA', 'status' => 'Desactivado'],
            ['codigo' => '9441', 'valor' => 'DOMINICANA REP', 'status' => 'Desactivado'],
            ['codigo' => '9444', 'valor' => 'ECUADOR', 'status' => 'Desactivado'],
            ['codigo' => '9446', 'valor' => 'EMIRAT ARAB UNI', 'status' => 'Desactivado'],
            ['codigo' => '9447', 'valor' => 'ESPAÑA', 'status' => 'Desactivado'],
            ['codigo' => '9450', 'valor' => 'EE UU', 'status' => 'Desactivado'],
            ['codigo' => '9453', 'valor' => 'ETIOPIA', 'status' => 'Desactivado'],
            ['codigo' => '9456', 'valor' => 'FIJI-ISLAS', 'status' => 'Desactivado'],
            ['codigo' => '9459', 'valor' => 'FILIPINAS', 'status' => 'Desactivado'],
            ['codigo' => '9462', 'valor' => 'FINLANDIA', 'status' => 'Desactivado'],
            ['codigo' => '9465', 'valor' => 'FRANCIA', 'status' => 'Desactivado'],
            ['codigo' => '9468', 'valor' => 'GABÓN', 'status' => 'Desactivado'],
            ['codigo' => '9471', 'valor' => 'GAMBIA', 'status' => 'Desactivado'],
            ['codigo' => '9474', 'valor' => 'GHANA', 'status' => 'Desactivado'],
            ['codigo' => '9477', 'valor' => 'GIBRALTAR', 'status' => 'Desactivado'],
            ['codigo' => '9480', 'valor' => 'GRECIA', 'status' => 'Desactivado'],
            ['codigo' => '9481', 'valor' => 'GRENADA', 'status' => 'Desactivado'],
            ['codigo' => '9483', 'valor' => 'GUATEMALA', 'status' => 'Desactivado'],
            ['codigo' => '9486', 'valor' => 'GUINEA', 'status' => 'Desactivado'],
            ['codigo' => '9487', 'valor' => 'GUYANA', 'status' => 'Desactivado'],
            ['codigo' => '9495', 'valor' => 'HAITÍ', 'status' => 'Desactivado'],
            ['codigo' => '9498', 'valor' => 'HOLANDA', 'status' => 'Desactivado'],
            ['codigo' => '9501', 'valor' => 'HONDURAS', 'status' => 'Desactivado'],
            ['codigo' => '9504', 'valor' => 'HONG KONG', 'status' => 'Desactivado'],
            ['codigo' => '9507', 'valor' => 'HUNGRÍA', 'status' => 'Desactivado'],
            ['codigo' => '9513', 'valor' => 'INDONESIA', 'status' => 'Desactivado'],
            ['codigo' => '9516', 'valor' => 'IRAK', 'status' => 'Desactivado'],
            ['codigo' => '9519', 'valor' => 'IRÁN', 'status' => 'Desactivado'],
            ['codigo' => '9522', 'valor' => 'IRLANDA', 'status' => 'Desactivado'],
            ['codigo' => '9525', 'valor' => 'ISLANDIA', 'status' => 'Desactivado'],
            ['codigo' => '9526', 'valor' => 'ISLAS SALOMÓN', 'status' => 'Desactivado'],
            ['codigo' => '9528', 'valor' => 'ISRAEL', 'status' => 'Desactivado'],
            ['codigo' => '9531', 'valor' => 'ITALIA', 'status' => 'Desactivado'],
            ['codigo' => '9534', 'valor' => 'JAMAICA', 'status' => 'Desactivado'],
            ['codigo' => '9537', 'valor' => 'JAPÓN', 'status' => 'Desactivado'],
            ['codigo' => '9540', 'valor' => 'JORDANIA', 'status' => 'Desactivado'],
            ['codigo' => '9543', 'valor' => 'KENIA', 'status' => 'Desactivado'],
            ['codigo' => '9544', 'valor' => 'KIRIBATI', 'status' => 'Desactivado'],
            ['codigo' => '9546', 'valor' => 'KUWAIT', 'status' => 'Desactivado'],
            ['codigo' => '9549', 'valor' => 'LAOS', 'status' => 'Desactivado'],
            ['codigo' => '9552', 'valor' => 'LESOTHO', 'status' => 'Desactivado'],
            ['codigo' => '9555', 'valor' => 'LÍBANO', 'status' => 'Desactivado'],
            ['codigo' => '9558', 'valor' => 'LIBERIA', 'status' => 'Desactivado'],
            ['codigo' => '9561', 'valor' => 'LIBIA', 'status' => 'Desactivado'],
            ['codigo' => '9564', 'valor' => 'LIECHTENSTEIN', 'status' => 'Desactivado'],
            ['codigo' => '9567', 'valor' => 'LUXEMBURGO', 'status' => 'Desactivado'],
            ['codigo' => '9570', 'valor' => 'MADAGASCAR', 'status' => 'Desactivado'],
            ['codigo' => '9573', 'valor' => 'MALASIA', 'status' => 'Desactivado'],
            ['codigo' => '9576', 'valor' => 'MALAWI', 'status' => 'Desactivado'],
            ['codigo' => '9577', 'valor' => 'MALDIVAS', 'status' => 'Desactivado'],
            ['codigo' => '9582', 'valor' => 'MALTA', 'status' => 'Desactivado'],
            ['codigo' => '9585', 'valor' => 'MARRUECOS', 'status' => 'Desactivado'],
            ['codigo' => '9591', 'valor' => 'MASCATE Y OMÁN', 'status' => 'Desactivado'],
            ['codigo' => '9594', 'valor' => 'MAURICIO', 'status' => 'Desactivado'],
            ['codigo' => '9597', 'valor' => 'MAURITANIA', 'status' => 'Desactivado'],
            ['codigo' => '9600', 'valor' => 'MÉXICO', 'status' => 'Desactivado'],
            ['codigo' => '9601', 'valor' => 'MICRONESIA', 'status' => 'Desactivado'],
            ['codigo' => '9603', 'valor' => 'MÓNACO', 'status' => 'Desactivado'],
            ['codigo' => '9606', 'valor' => 'MONGOLIA', 'status' => 'Desactivado'],
            ['codigo' => '9609', 'valor' => 'MOZAMBIQUE', 'status' => 'Desactivado'],
            ['codigo' => '9611', 'valor' => 'NAURU', 'status' => 'Desactivado'],
            ['codigo' => '9612', 'valor' => 'NEPAL', 'status' => 'Desactivado'],
            ['codigo' => '9615', 'valor' => 'NICARAGUA', 'status' => 'Desactivado'],
            ['codigo' => '9618', 'valor' => 'NÍGER', 'status' => 'Desactivado'],
            ['codigo' => '9621', 'valor' => 'NIGERIA', 'status' => 'Desactivado'],
            ['codigo' => '9624', 'valor' => 'NORUEGA', 'status' => 'Desactivado'],
            ['codigo' => '9627', 'valor' => 'NVA CALEDONIA', 'status' => 'Desactivado'],
            ['codigo' => '9633', 'valor' => 'NVA ZELANDIA', 'status' => 'Desactivado'],
            ['codigo' => '9636', 'valor' => 'NUEVAS HEBRIDAS', 'status' => 'Desactivado'],
            ['codigo' => '9638', 'valor' => 'PAPUA NV GUINEA', 'status' => 'Desactivado'],
            ['codigo' => '9639', 'valor' => 'PAKISTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9642', 'valor' => 'PANAMÁ', 'status' => 'Desactivado'],
            ['codigo' => '9645', 'valor' => 'PARAGUAY', 'status' => 'Desactivado'],
            ['codigo' => '9648', 'valor' => 'PERÚ', 'status' => 'Desactivado'],
            ['codigo' => '9651', 'valor' => 'POLONIA', 'status' => 'Desactivado'],
            ['codigo' => '9660', 'valor' => 'QATAR EL', 'status' => 'Desactivado'],
            ['codigo' => '9663', 'valor' => 'REINO UNIDO', 'status' => 'Desactivado'],
            ['codigo' => '9666', 'valor' => 'EGIPTO', 'status' => 'Desactivado'],
            ['codigo' => '9669', 'valor' => 'RODESIA', 'status' => 'Desactivado'],
            ['codigo' => '9672', 'valor' => 'RUANDA', 'status' => 'Desactivado'],
            ['codigo' => '9675', 'valor' => 'RUMANIA', 'status' => 'Desactivado'],
            ['codigo' => '9677', 'valor' => 'SAN MARINO', 'status' => 'Desactivado'],
            ['codigo' => '9678', 'valor' => 'SAMOA OCCID', 'status' => 'Desactivado'],
            ['codigo' => '9679', 'valor' => 'SAINT KITTS AND NEVIS', 'status' => 'Desactivado'],
            ['codigo' => '9680', 'valor' => 'SANTA LUCIA', 'status' => 'Desactivado'],
            ['codigo' => '9681', 'valor' => 'SENEGAL', 'status' => 'Desactivado'],
            ['codigo' => '9682', 'valor' => 'SAOTOME Y PRINC', 'status' => 'Desactivado'],
            ['codigo' => '9683', 'valor' => 'SN VIC Y GRENAD', 'status' => 'Desactivado'],
            ['codigo' => '9684', 'valor' => 'SIERRA LEONA', 'status' => 'Desactivado'], 
            ['codigo' => '9687', 'valor' => 'SINGAPUR', 'status' => 'Desactivado'],
            ['codigo' => '9690', 'valor' => 'SIRIA', 'status' => 'Desactivado'],
            ['codigo' => '9691', 'valor' => 'SEYCHELLES', 'status' => 'Desactivado'],
            ['codigo' => '9693', 'valor' => 'SOMALIA', 'status' => 'Desactivado'],
            ['codigo' => '9696', 'valor' => 'SUDÁFRICA REP', 'status' => 'Desactivado'],
            ['codigo' => '9699', 'valor' => 'SUDAN', 'status' => 'Desactivado'],
            ['codigo' => '9702', 'valor' => 'SUECIA', 'status' => 'Desactivado'],
            ['codigo' => '9705', 'valor' => 'SUIZA', 'status' => 'Desactivado'],
            ['codigo' => '9706', 'valor' => 'SURINAM', 'status' => 'Desactivado'],
            ['codigo' => '9707', 'valor' => 'SRI LANKA', 'status' => 'Desactivado'],
            ['codigo' => '9708', 'valor' => 'SUECILANDIA', 'status' => 'Desactivado'],
            ['codigo' => '9714', 'valor' => 'TANZANIA', 'status' => 'Desactivado'],
            ['codigo' => '9717', 'valor' => 'TOGO', 'status' => 'Desactivado'],
            ['codigo' => '9720', 'valor' => 'TRINIDAD TOBAGO', 'status' => 'Desactivado'],
            ['codigo' => '9722', 'valor' => 'TONGA', 'status' => 'Desactivado'],
            ['codigo' => '9723', 'valor' => 'TÚNEZ', 'status' => 'Desactivado'],
            ['codigo' => '9725', 'valor' => 'TRANSKEI', 'status' => 'Desactivado'],
            ['codigo' => '9726', 'valor' => 'TURQUÍA', 'status' => 'Desactivado'],
            ['codigo' => '9727', 'valor' => 'TUVALU', 'status' => 'Desactivado'],
            ['codigo' => '9729', 'valor' => 'UGANDA', 'status' => 'Desactivado'],
            ['codigo' => '9732', 'valor' => 'U R S S', 'status' => 'Desactivado'],
            ['codigo' => '9735', 'valor' => 'URUGUAY', 'status' => 'Desactivado'],
            ['codigo' => '9738', 'valor' => 'VATICANO', 'status' => 'Desactivado'],
            ['codigo' => '9739', 'valor' => 'VANUATU', 'status' => 'Desactivado'],
            ['codigo' => '9740', 'valor' => 'VENDA', 'status' => 'Desactivado'],
            ['codigo' => '9741', 'valor' => 'VENEZUELA', 'status' => 'Desactivado'],
            ['codigo' => '9744', 'valor' => 'VIETNAM NORTE', 'status' => 'Desactivado'],
            ['codigo' => '9747', 'valor' => 'VIETNAM SUR', 'status' => 'Desactivado'],
            ['codigo' => '9750', 'valor' => 'YEMEN SUR REP', 'status' => 'Desactivado'],
            ['codigo' => '9756', 'valor' => 'YUGOSLAVIA', 'status' => 'Desactivado'],
            ['codigo' => '9758', 'valor' => 'ZAIRE', 'status' => 'Desactivado'],
            ['codigo' => '9759', 'valor' => 'ZAMBIA', 'status' => 'Desactivado'],
            ['codigo' => '9760', 'valor' => 'ZIMBABWE', 'status' => 'Desactivado'],
            ['codigo' => '9850', 'valor' => 'PUERTO RICO', 'status' => 'Desactivado'],
            ['codigo' => '9862', 'valor' => 'BAHAMAS', 'status' => 'Desactivado'],  
            ['codigo' => '9863', 'valor' => 'BERMUDAS', 'status' => 'Desactivado'],
            ['codigo' => '9865', 'valor' => 'MARTINICA', 'status' => 'Desactivado'],
            ['codigo' => '9886', 'valor' => 'NUEVA GUINEA', 'status' => 'Desactivado'],
            ['codigo' => '9898', 'valor' => 'ANT HOLANDESAS', 'status' => 'Desactivado'],
            ['codigo' => '9899', 'valor' => 'TAIWÁN', 'status' => 'Desactivado'],
            ['codigo' => '9897', 'valor' => 'ISLAS VÍRGENES BRITÁNICAS', 'status' => 'Desactivado'],
            ['codigo' => '9887', 'valor' => 'ISLAS GRAN CAIMÁN', 'status' => 'Desactivado'],
            ['codigo' => '9571', 'valor' => 'MACEDONIA', 'status' => 'Desactivado'],
            ['codigo' => '9300', 'valor' => 'EL SALVADOR', 'status' => 'Desactivado'],
            ['codigo' => '9369', 'valor' => 'BULGARIA', 'status' => 'Desactivado'],
            ['codigo' => '9439', 'valor' => 'DJIBOUTI', 'status' => 'Desactivado'],
            ['codigo' => '9510', 'valor' => 'INDIA', 'status' => 'Desactivado'],
            ['codigo' => '9579', 'valor' => 'MALI', 'status' => 'Desactivado'],
            ['codigo' => '9654', 'valor' => 'PORTUGAL', 'status' => 'Desactivado'],
            ['codigo' => '9711', 'valor' => 'TAILANDIA', 'status' => 'Desactivado'],
            ['codigo' => '9736', 'valor' => 'UCRANIA', 'status' => 'Desactivado'],
            ['codigo' => '9737', 'valor' => 'UZBEKISTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9640', 'valor' => 'PALESTINA', 'status' => 'Desactivado'],
            ['codigo' => '9641', 'valor' => 'CROACIA', 'status' => 'Desactivado'],
            ['codigo' => '9673', 'valor' => 'REPÚBLICA DE ARMENIA', 'status' => 'Desactivado'],
            ['codigo' => '9472', 'valor' => 'GEORGIA', 'status' => 'Desactivado'],
            ['codigo' => '9311', 'valor' => 'ALEMANIA', 'status' => 'Desactivado'],
            ['codigo' => '9733', 'valor' => 'RUSIA', 'status' => 'Desactivado'],
            ['codigo' => '9541', 'valor' => 'KAZAKISTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9746', 'valor' => 'VIETNAM', 'status' => 'Desactivado'],
            ['codigo' => '9551', 'valor' => 'LETONIA', 'status' => 'Desactivado'],
            ['codigo' => '9451', 'valor' => 'ESLOVENIA', 'status' => 'Desactivado'],
            ['codigo' => '9338', 'valor' => 'AZERBAIYÁN', 'status' => 'Desactivado'],
            ['codigo' => '9353', 'valor' => 'BIELORRUSIA', 'status' => 'Desactivado'],
            ['codigo' => '9482', 'valor' => 'GROENLANDIA', 'status' => 'Desactivado'],
            ['codigo' => '9494', 'valor' => 'GUINEA-BISSAU', 'status' => 'Desactivado'],
            ['codigo' => '9524', 'valor' => 'ISLA DE COCOS', 'status' => 'Desactivado'],
            ['codigo' => '9304', 'valor' => 'ÅLAND', 'status' => 'Desactivado'],
            ['codigo' => '9332', 'valor' => 'ARUBA', 'status' => 'Desactivado'], 
            ['codigo' => '9454', 'valor' => 'ERITREA', 'status' => 'Desactivado'],
            ['codigo' => '9457', 'valor' => 'ESTONIA', 'status' => 'Desactivado'],
            ['codigo' => '9489', 'valor' => 'GUADALUPE', 'status' => 'Desactivado'],
            ['codigo' => '9491', 'valor' => 'GUAYANA FRANCESA', 'status' => 'Desactivado'],
            ['codigo' => '9492', 'valor' => 'GUERNSEY', 'status' => 'Desactivado'],
            ['codigo' => '9523', 'valor' => 'ISLA DE NAVIDAD', 'status' => 'Desactivado'],
            ['codigo' => '9530', 'valor' => 'ISLAS AZORES', 'status' => 'Desactivado'],
            ['codigo' => '9532', 'valor' => 'ISLA QESHM', 'status' => 'Desactivado'],
            ['codigo' => '9535', 'valor' => 'ISLAS MARIANAS DEL NORTE', 'status' => 'Desactivado'],
            ['codigo' => '9542', 'valor' => 'ISLAS ULTRAMARINAS DE EE. UU.', 'status' => 'Desactivado'],
            ['codigo' => '9547', 'valor' => 'JERSEY', 'status' => 'Desactivado'],
            ['codigo' => '9548', 'valor' => 'KIRGUISTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9574', 'valor' => 'MALI', 'status' => 'Desactivado'],
            ['codigo' => '9598', 'valor' => 'MAYOTTE', 'status' => 'Desactivado'],
            ['codigo' => '9602', 'valor' => 'MOLDAVIA', 'status' => 'Desactivado'],
            ['codigo' => '9607', 'valor' => 'MONTENEGRO', 'status' => 'Desactivado'],
            ['codigo' => '9608', 'valor' => 'MONSERRAT', 'status' => 'Desactivado'],
            ['codigo' => '9623', 'valor' => 'NORFOLK', 'status' => 'Desactivado'],
            ['codigo' => '9652', 'valor' => 'POLINESIA FRANCESA', 'status' => 'Desactivado'],
            ['codigo' => '9692', 'valor' => 'SVALBARD Y JAN MAYEN', 'status' => 'Desactivado'],
            ['codigo' => '9709', 'valor' => 'TAYIKISTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9712', 'valor' => 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'status' => 'Desactivado'],
            ['codigo' => '9716', 'valor' => 'TIMOR ORIENTAL', 'status' => 'Desactivado'],
            ['codigo' => '9718', 'valor' => 'TOKELAU', 'status' => 'Desactivado'],
            ['codigo' => '9719', 'valor' => 'TURKMENISTÁN', 'status' => 'Desactivado'],
            ['codigo' => '9751', 'valor' => 'YIBUTI', 'status' => 'Desactivado'],
            ['codigo' => '9452', 'valor' => 'WALLIS Y FUTUNA', 'status' => 'Desactivado'],
            ['codigo' => '9901', 'valor' => 'NEVADA (USA)', 'status' => 'Desactivado'],
            ['codigo' => '9902', 'valor' => 'WYOMING (USA)', 'status' => 'Desactivado'],
            ['codigo' => '9903', 'valor' => 'CAMPIONE D\'ITALIA, ITALIA', 'status' => 'Desactivado'],
            ['codigo' => '9664', 'valor' => 'REPÚBLICA CHECA', 'status' => 'Desactivado'],
            ['codigo' => '9415', 'valor' => 'CURAZAO', 'status' => 'Desactivado'],
            ['codigo' => '9904', 'valor' => 'FLORIDA (USA)', 'status' => 'Desactivado'],
            ['codigo' => '9514', 'valor' => 'INGLATERRA Y GALES', 'status' => 'Desactivado'],
            ['codigo' => '9906', 'valor' => 'TEXAS (USA)', 'status' => 'Desactivado'],
            ['codigo' => '9359', 'valor' => 'BOSNIA Y HERZEGOVINA', 'status' => 'Desactivado'],
            ['codigo' => '9493', 'valor' => 'GUINEA ECUATORIAL', 'status' => 'Desactivado'],
            ['codigo' => '9521', 'valor' => 'ISLA DE MAN', 'status' => 'Desactivado'],
            ['codigo' => '9533', 'valor' => 'ISLAS MALVINAS', 'status' => 'Desactivado'],
            ['codigo' => '9538', 'valor' => 'ISLAS PITCAIRN', 'status' => 'Desactivado'],
            ['codigo' => '9689', 'valor' => 'SERBIA', 'status' => 'Desactivado'],
            ['codigo' => '9713', 'valor' => 'TERRITORIOS AUSTRales FRANCESES', 'status' => 'Desactivado'],
            ['codigo' => '9449', 'valor' => 'ESLOVAQUIA', 'status' => 'Desactivado'],
            ['codigo' => '9888', 'valor' => 'SAN MAARTEN', 'status' => 'Desactivado'],
            ['codigo' => '9490', 'valor' => 'GUAM', 'status' => 'Desactivado'],
            ['codigo' => '9527', 'valor' => 'ISLAS COOK', 'status' => 'Desactivado'],
            ['codigo' => '9529', 'valor' => 'ISLAS FEROE', 'status' => 'Desactivado'],
            ['codigo' => '9536', 'valor' => 'ISLAS MARSHALL', 'status' => 'Desactivado'],
            ['codigo' => '9545', 'valor' => 'ISLAS VÍRGENES ESTADOUNIDENSES', 'status' => 'Desactivado'],
            ['codigo' => '9568', 'valor' => 'MACAO', 'status' => 'Desactivado'],
            ['codigo' => '9610', 'valor' => 'NAMIBIA', 'status' => 'Desactivado'],
            ['codigo' => '9622', 'valor' => 'NIUE', 'status' => 'Desactivado'],
            ['codigo' => '9643', 'valor' => 'PALAOS', 'status' => 'Desactivado'],
            ['codigo' => '9667', 'valor' => 'REUNIÓN', 'status' => 'Desactivado'],
            ['codigo' => '9676', 'valor' => 'SAHARA OCCIDENTAL', 'status' => 'Desactivado'],
            ['codigo' => '9685', 'valor' => 'SAMOA AMERICANA', 'status' => 'Desactivado'],
            ['codigo' => '9686', 'valor' => 'SAN PEDRO Y MIQUELÓN', 'status' => 'Desactivado'],
            ['codigo' => '9688', 'valor' => 'SANTA ELENA', 'status' => 'Desactivado'],
            ['codigo' => '9715', 'valor' => 'TERRITORIOS PALESTINOS', 'status' => 'Desactivado'],
            ['codigo' => '9900', 'valor' => 'DELAWARE (USA)', 'status' => 'Desactivado'],
            ['codigo' => '9371', 'valor' => 'BURKINA FASO', 'status' => 'Desactivado'],
            ['codigo' => '9376', 'valor' => 'CABINDA', 'status' => 'Desactivado'],
            ['codigo' => '9907', 'valor' => 'WASHINGTON (USA)', 'status' => 'Desactivado'],
        ];  

        DB::table('pais')->insert($pais);
    }
}
