<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pais = [
            [
                ['codigo' => 'AF', 'valor' => 'Afganistan', 'status' => 'Desactivado'],
                ['codigo' => 'AX', 'valor' => 'Aland', 'status' => 'Desactivado'],
                ['codigo' => 'AL', 'valor' => 'Albania', 'status' => 'Desactivado'],
                ['codigo' => 'DE', 'valor' => 'Alemania', 'status' => 'Desactivado'],
                ['codigo' => 'AD', 'valor' => 'Andorra', 'status' => 'Desactivado'],
                ['codigo' => 'AO', 'valor' => 'Angola', 'status' => 'Desactivado'],
                ['codigo' => 'AI', 'valor' => 'Anguilla', 'status' => 'Desactivado'],
                ['codigo' => 'AQ', 'valor' => 'Antartida', 'status' => 'Desactivado'],
                ['codigo' => 'AG', 'valor' => 'Antigua y Barbuda', 'status' => 'Desactivado'],
                ['codigo' => 'SA', 'valor' => 'Arabia Saudita', 'status' => 'Desactivado'],
                ['codigo' => 'DZ', 'valor' => 'Argelia', 'status' => 'Desactivado'],
                ['codigo' => 'AR', 'valor' => 'Argentina', 'status' => 'Desactivado'],
                ['codigo' => 'AM', 'valor' => 'Armenia', 'status' => 'Desactivado'],
                ['codigo' => 'AW', 'valor' => 'Aruba', 'status' => 'Desactivado'],
                ['codigo' => 'AU', 'valor' => 'Australia', 'status' => 'Desactivado'],
                ['codigo' => 'AT', 'valor' => 'Austria', 'status' => 'Desactivado'],
                ['codigo' => 'AZ', 'valor' => 'Azerbaiyan', 'status' => 'Desactivado'],
                ['codigo' => 'BS', 'valor' => 'Bahamas', 'status' => 'Desactivado'],
                ['codigo' => 'BH', 'valor' => 'Bahrein', 'status' => 'Desactivado'],
                ['codigo' => 'BD', 'valor' => 'Bangladesh', 'status' => 'Desactivado'],
                ['codigo' => 'BB', 'valor' => 'Barbados', 'status' => 'Desactivado'],
                ['codigo' => 'BY', 'valor' => 'Bielorrusia', 'status' => 'Desactivado'],
                ['codigo' => 'BE', 'valor' => 'Belgica', 'status' => 'Desactivado'],
                ['codigo' => 'BZ', 'valor' => 'Belice', 'status' => 'Desactivado'],
                ['codigo' => 'BJ', 'valor' => 'Benin', 'status' => 'Desactivado'],
                ['codigo' => 'BM', 'valor' => 'Bermudas', 'status' => 'Desactivado'],
                ['codigo' => 'BT', 'valor' => 'Butan', 'status' => 'Desactivado'],
                ['codigo' => 'BO', 'valor' => 'Bolivia', 'status' => 'Desactivado'],
                ['codigo' => 'BA', 'valor' => 'Bosnia y Herzegovina', 'status' => 'Desactivado'],
                ['codigo' => 'BW', 'valor' => 'Botswana', 'status' => 'Desactivado'],
                ['codigo' => 'BR', 'valor' => 'Brasil', 'status' => 'Desactivado'],
                ['codigo' => 'BN', 'valor' => 'Brunei Darussalam', 'status' => 'Desactivado'],
                ['codigo' => 'BG', 'valor' => 'Bulgaria', 'status' => 'Desactivado'],
                ['codigo' => 'BF', 'valor' => 'Burkina Faso', 'status' => 'Desactivado'],
                ['codigo' => 'BI', 'valor' => 'Burundi', 'status' => 'Desactivado'],
                ['codigo' => 'CV', 'valor' => 'Cabo Verde', 'status' => 'Desactivado'],
                ['codigo' => 'KH', 'valor' => 'Camboya', 'status' => 'Desactivado'],
                ['codigo' => 'CM', 'valor' => 'Camerun', 'status' => 'Desactivado'],
                ['codigo' => 'CA', 'valor' => 'Canada', 'status' => 'Desactivado'],
                ['codigo' => 'TD', 'valor' => 'Chad', 'status' => 'Desactivado'],
                ['codigo' => 'CL', 'valor' => 'Chile', 'status' => 'Desactivado'],
                ['codigo' => 'CN', 'valor' => 'China', 'status' => 'Desactivado'],
                ['codigo' => 'CY', 'valor' => 'Chipre', 'status' => 'Desactivado'],
                ['codigo' => 'VA', 'valor' => 'Ciudad del Vaticano', 'status' => 'Desactivado'],
                ['codigo' => 'CO', 'valor' => 'Colombia', 'status' => 'Desactivado'],
                ['codigo' => 'KM', 'valor' => 'Comores', 'status' => 'Desactivado'],
                ['codigo' => 'CG', 'valor' => 'Congo', 'status' => 'Desactivado'],
                ['codigo' => 'KR', 'valor' => 'Corea del Sur', 'status' => 'Desactivado'],
                ['codigo' => 'KP', 'valor' => 'Corea del Norte', 'status' => 'Desactivado'],
                ['codigo' => 'CR', 'valor' => 'Costa Rica', 'status' => 'Desactivado'],
                ['codigo' => 'CI', 'valor' => 'Costa de Marfil', 'status' => 'Desactivado'],
                ['codigo' => 'HR', 'valor' => 'Croacia', 'status' => 'Desactivado'],
                ['codigo' => 'CU', 'valor' => 'Cuba', 'status' => 'Desactivado'],
                ['codigo' => 'CW', 'valor' => 'Curazao', 'status' => 'Desactivado'],
                ['codigo' => 'DK', 'valor' => 'Dinamarca', 'status' => 'Desactivado'],
                ['codigo' => 'DJ', 'valor' => 'Djibouti', 'status' => 'Desactivado'],
                ['codigo' => 'DM', 'valor' => 'Dominica', 'status' => 'Desactivado'],
                ['codigo' => 'EC', 'valor' => 'Ecuador', 'status' => 'Desactivado'],
                ['codigo' => 'EG', 'valor' => 'Egipto', 'status' => 'Desactivado'],
                ['codigo' => 'SV', 'valor' => 'El Salvador', 'status' => 'Desactivado'],
                ['codigo' => 'AE', 'valor' => 'Emiratos Arabes Unidos', 'status' => 'Desactivado'],
                ['codigo' => 'ER', 'valor' => 'Eritrea', 'status' => 'Desactivado'],
                ['codigo' => 'SK', 'valor' => 'Eslovaquia', 'status' => 'Desactivado'],
                ['codigo' => 'SI', 'valor' => 'Eslovenia', 'status' => 'Desactivado'],
                ['codigo' => 'ES', 'valor' => 'España', 'status' => 'Desactivado'],
                ['codigo' => 'US', 'valor' => 'Estados Unidos', 'status' => 'Desactivado'],
                ['codigo' => 'EE', 'valor' => 'Estonia', 'status' => 'Desactivado'],
                ['codigo' => 'ET', 'valor' => 'Etiopia', 'status' => 'Desactivado'],
                ['codigo' => 'PH', 'valor' => 'Filipinas', 'status' => 'Desactivado'],
                ['codigo' => 'FI', 'valor' => 'Finlandia', 'status' => 'Desactivado'],
                ['codigo' => 'FJ', 'valor' => 'Fiyi', 'status' => 'Desactivado'],
                ['codigo' => 'FR', 'valor' => 'Francia', 'status' => 'Desactivado'],
                ['codigo' => 'GA', 'valor' => 'Gabon', 'status' => 'Desactivado'],
                ['codigo' => 'GM', 'valor' => 'Gambia', 'status' => 'Desactivado'],
                ['codigo' => 'GE', 'valor' => 'Georgia', 'status' => 'Desactivado'],
                ['codigo' => 'GH', 'valor' => 'Ghana', 'status' => 'Desactivado'],
                ['codigo' => 'GI', 'valor' => 'Gibraltar', 'status' => 'Desactivado'],
                ['codigo' => 'GR', 'valor' => 'Grecia', 'status' => 'Desactivado'],
                ['codigo' => 'GL', 'valor' => 'Groenlandia', 'status' => 'Desactivado'],
                ['codigo' => 'GP', 'valor' => 'Guadalupe', 'status' => 'Desactivado'],
                ['codigo' => 'GU', 'valor' => 'Guam', 'status' => 'Desactivado'],
                ['codigo' => 'GT', 'valor' => 'Guatemala', 'status' => 'Desactivado'],
                ['codigo' => 'GF', 'valor' => 'Guayana Francesa', 'status' => 'Desactivado'],
                ['codigo' => 'GN', 'valor' => 'Guinea', 'status' => 'Desactivado'],
                ['codigo' => 'GQ', 'valor' => 'Guinea Ecuatorial', 'status' => 'Desactivado'],
                ['codigo' => 'GW', 'valor' => 'Guinea-Bissau', 'status' => 'Desactivado'],
                ['codigo' => 'GY', 'valor' => 'Guyana', 'status' => 'Desactivado'],
                ['codigo' => 'HT', 'valor' => 'Haiti', 'status' => 'Desactivado'],
                ['codigo' => 'HN', 'valor' => 'Honduras', 'status' => 'Desactivado'],
                ['codigo' => 'HK', 'valor' => 'Hong Kong', 'status' => 'Desactivado'],
                ['codigo' => 'HU', 'valor' => 'Hungria', 'status' => 'Desactivado'],
                ['codigo' => 'IN', 'valor' => 'India', 'status' => 'Desactivado'],
                ['codigo' => 'ID', 'valor' => 'Indonesia', 'status' => 'Desactivado'],
                ['codigo' => 'IR', 'valor' => 'Iran', 'status' => 'Desactivado'],
                ['codigo' => 'IQ', 'valor' => 'Irak', 'status' => 'Desactivado'],
                ['codigo' => 'IE', 'valor' => 'Irlanda', 'status' => 'Desactivado'],
                ['codigo' => 'IS', 'valor' => 'Islandia', 'status' => 'Desactivado'],
                ['codigo' => 'IL', 'valor' => 'Israel', 'status' => 'Desactivado'],
                ['codigo' => 'IT', 'valor' => 'Italia', 'status' => 'Desactivado'],
                ['codigo' => 'JM', 'valor' => 'Jamaica', 'status' => 'Desactivado'],
                ['codigo' => 'JP', 'valor' => 'Japon', 'status' => 'Desactivado'],
                ['codigo' => 'JO', 'valor' => 'Jordania', 'status' => 'Desactivado'],
                ['codigo' => 'KZ', 'valor' => 'Kazajistán', 'status' => 'Desactivado'],
                ['codigo' => 'KE', 'valor' => 'Kenia', 'status' => 'Desactivado'],
                ['codigo' => 'KG', 'valor' => 'Kirguistán', 'status' => 'Desactivado'],
                ['codigo' => 'KI', 'valor' => 'Kiribati', 'status' => 'Desactivado'],
                ['codigo' => 'KW', 'valor' => 'Kuwait', 'status' => 'Desactivado'],
                ['codigo' => 'LA', 'valor' => 'Laos, República Democrática', 'status' => 'Desactivado'],
                ['codigo' => 'LS', 'valor' => 'Lesotho', 'status' => 'Desactivado'],
                ['codigo' => 'LV', 'valor' => 'Letonia', 'status' => 'Desactivado'],
                ['codigo' => 'LB', 'valor' => 'Líbano', 'status' => 'Desactivado'],
                ['codigo' => 'LR', 'valor' => 'Liberia', 'status' => 'Desactivado'],
                ['codigo' => 'LY', 'valor' => 'Libia', 'status' => 'Desactivado'],
                ['codigo' => 'LI', 'valor' => 'Liechtenstein', 'status' => 'Desactivado'],
                ['codigo' => 'LT', 'valor' => 'Lituania', 'status' => 'Desactivado'],
                ['codigo' => 'LU', 'valor' => 'Luxemburgo', 'status' => 'Desactivado'],
                ['codigo' => 'MO', 'valor' => 'Macao', 'status' => 'Desactivado'],
                ['codigo' => 'MK', 'valor' => 'Macedonia', 'status' => 'Desactivado'],
                ['codigo' => 'MG', 'valor' => 'Madagascar', 'status' => 'Desactivado'],
                ['codigo' => 'MY', 'valor' => 'Malasia', 'status' => 'Desactivado'],
                ['codigo' => 'MW', 'valor' => 'Malawi', 'status' => 'Desactivado'],
                ['codigo' => 'MV', 'valor' => 'Maldivas', 'status' => 'Desactivado'],
                ['codigo' => 'ML', 'valor' => 'Malí', 'status' => 'Desactivado'],
                ['codigo' => 'MT', 'valor' => 'Malta', 'status' => 'Desactivado'],
                ['codigo' => 'MA', 'valor' => 'Marruecos', 'status' => 'Desactivado'],
                ['codigo' => 'MO', 'valor' => 'Martinica e.a.', 'status' => 'Desactivado'],
                ['codigo' => 'MU', 'valor' => 'Mauricio', 'status' => 'Desactivado'],
                ['codigo' => 'MR', 'valor' => 'Mauritania', 'status' => 'Desactivado'],
                ['codigo' => 'YT', 'valor' => 'Mayotte', 'status' => 'Desactivado'],
                ['codigo' => 'MX', 'valor' => 'Mexico', 'status' => 'Desactivado'],
                ['codigo' => 'FM', 'valor' => 'Micronesia', 'status' => 'Desactivado'],
                ['codigo' => 'MD', 'valor' => 'Moldavia, Republica de', 'status' => 'Desactivado'],
                ['codigo' => 'MC', 'valor' => 'Monaco', 'status' => 'Desactivado'],
                ['codigo' => 'MN', 'valor' => 'Mongolia', 'status' => 'Desactivado'],
                ['codigo' => 'ME', 'valor' => 'Montenegro', 'status' => 'Desactivado'],
                ['codigo' => 'MS', 'valor' => 'Montserrat', 'status' => 'Desactivado'],
                ['codigo' => 'MZ', 'valor' => 'Mozambique', 'status' => 'Desactivado'],
                ['codigo' => 'MM', 'valor' => 'Myanmar', 'status' => 'Desactivado'],
                ['codigo' => 'NA', 'valor' => 'Namibia', 'status' => 'Desactivado'],
                ['codigo' => 'NR', 'valor' => 'Nauru', 'status' => 'Desactivado'],
                ['codigo' => 'NP', 'valor' => 'Nepal', 'status' => 'Desactivado'],
                ['codigo' => 'NI', 'valor' => 'Nicaragua', 'status' => 'Desactivado'],
                ['codigo' => 'NE', 'valor' => 'Nfger', 'status' => 'Desactivado'],
                ['codigo' => 'NG', 'valor' => 'Nigeria', 'status' => 'Desactivado'],
                ['codigo' => 'NU', 'valor' => 'Niue', 'status' => 'Desactivado'],
                ['codigo' => 'NO', 'valor' => 'Noruega', 'status' => 'Desactivado'],
                ['codigo' => 'NC', 'valor' => 'Nueva Caledonia', 'status' => 'Desactivado'],
                ['codigo' => 'NZ', 'valor' => 'Nueva Zelanda', 'status' => 'Desactivado'],
                ['codigo' => 'OM', 'valor' => 'Oman', 'status' => 'Desactivado'],
                ['codigo' => 'NL', 'valor' => 'Pafses Bajos', 'status' => 'Desactivado'],
                ['codigo' => 'PK', 'valor' => 'Pakistan', 'status' => 'Desactivado'],
                ['codigo' => 'PW', 'valor' => 'Palaos', 'status' => 'Desactivado'],
                ['codigo' => 'PS', 'valor' => 'Palestina', 'status' => 'Desactivado'],
                ['codigo' => 'PA', 'valor' => 'Panama', 'status' => 'Desactivado'],
                ['codigo' => 'PG', 'valor' => 'Papua, Nueva Guinea', 'status' => 'Desactivado'],
                ['codigo' => 'PY', 'valor' => 'Paraguay', 'status' => 'Desactivado'],
                ['codigo' => 'PE', 'valor' => 'Peru', 'status' => 'Desactivado'],
                ['codigo' => 'PF', 'valor' => 'Polinesia Francesa', 'status' => 'Desactivado'],
                ['codigo' => 'PL', 'valor' => 'Polonia', 'status' => 'Desactivado'],
                ['codigo' => 'PT', 'valor' => 'Portugal', 'status' => 'Desactivado'],
                ['codigo' => 'PR', 'valor' => 'Puerto Rico', 'status' => 'Desactivado'],
                ['codigo' => 'QA', 'valor' => 'Qatar', 'status' => 'Desactivado'],
                ['codigo' => 'GB', 'valor' => 'Reino Unido', 'status' => 'Desactivado'],
                ['codigo' => 'KP', 'valor' => 'República Democrática Popular de Corea', 'status' => 'Desactivado'],
                ['codigo' => 'CZ', 'valor' => 'República Checa', 'status' => 'Desactivado'],
                ['codigo' => 'KR', 'valor' => 'República de Corea', 'status' => 'Desactivado'],
                ['codigo' => 'CD', 'valor' => 'República Democrática del Congo', 'status' => 'Desactivado'],
                ['codigo' => 'DO', 'valor' => 'República Dominicana', 'status' => 'Desactivado'],
                ['codigo' => 'IR', 'valor' => 'República Islámica de Irán', 'status' => 'Desactivado'],
                ['codigo' => 'RE', 'valor' => 'Reunión', 'status' => 'Desactivado'],
                ['codigo' => 'RW', 'valor' => 'Ruanda', 'status' => 'Desactivado'],
                ['codigo' => 'RO', 'valor' => 'Rumania', 'status' => 'Desactivado'],
                ['codigo' => 'RU', 'valor' => 'Rusia', 'status' => 'Desactivado'],
                ['codigo' => 'EH', 'valor' => 'Sahara Occidental', 'status' => 'Desactivado'],
                ['codigo' => 'BL', 'valor' => 'San Bartolomé', 'status' => 'Desactivado'],
                ['codigo' => 'MF', 'valor' => 'San Martín (parte francesa)', 'status' => 'Desactivado'],
                ['codigo' => 'SB', 'valor' => 'Islas Salomón', 'status' => 'Desactivado'],
                ['codigo' => 'WS', 'valor' => 'Samoa', 'status' => 'Desactivado'],
                ['codigo' => 'AS', 'valor' => 'Samoa Americana', 'status' => 'Desactivado'],
                ['codigo' => 'KN', 'valor' => 'San Cristóbal y Nieves', 'status' => 'Desactivado'],
                ['codigo' => 'SM', 'valor' => 'San Marino', 'status' => 'Desactivado'],
                ['codigo' => 'PM', 'valor' => 'San Pedro y Miquelón', 'status' => 'Desactivado'],
                ['codigo' => 'VC', 'valor' => 'San Vicente y las Granadinas', 'status' => 'Desactivado'],
                ['codigo' => 'SH', 'valor' => 'Santa Elena', 'status' => 'Desactivado'],
                ['codigo' => 'LC', 'valor' => 'Santa Lucía', 'status' => 'Desactivado'],
                ['codigo' => 'ST', 'valor' => 'Santo Tomé y Príncipe', 'status' => 'Desactivado'],
                ['codigo' => 'SN', 'valor' => 'Senegal', 'status' => 'Desactivado'],
                ['codigo' => 'RS', 'valor' => 'Serbia', 'status' => 'Desactivado'],
                ['codigo' => 'SC', 'valor' => 'Seychelles', 'status' => 'Desactivado'],
                ['codigo' => 'SL', 'valor' => 'Sierra Leona', 'status' => 'Desactivado'],
                ['codigo' => 'SG', 'valor' => 'Singapur', 'status' => 'Desactivado'],
                ['codigo' => 'SX', 'valor' => 'Sint Maarten (parte holandesa)', 'status' => 'Desactivado'],
                ['codigo' => 'SY', 'valor' => 'Siria', 'status' => 'Desactivado'],
                ['codigo' => 'SO', 'valor' => 'Somalia', 'status' => 'Desactivado'],
                ['codigo' => 'SS', 'valor' => 'Sudán del Sur', 'status' => 'Desactivado'],
                ['codigo' => 'LK', 'valor' => 'Sri Lanka', 'status' => 'Desactivado'],
                ['codigo' => 'ZA', 'valor' => 'Sudáfrica', 'status' => 'Desactivado'],
                ['codigo' => 'SD', 'valor' => 'Sudán', 'status' => 'Desactivado'],
                ['codigo' => 'SE', 'valor' => 'Suecia', 'status' => 'Desactivado'],
                ['codigo' => 'CH', 'valor' => 'Suiza', 'status' => 'Desactivado'],
                ['codigo' => 'SR', 'valor' => 'Surinam', 'status' => 'Desactivado'],
                ['codigo' => 'SJ', 'valor' => 'Svalbard y Jan Mayen', 'status' => 'Desactivado'],
                ['codigo' => 'SZ', 'valor' => 'Swazilandia', 'status' => 'Desactivado'],
                ['codigo' => 'TH', 'valor' => 'Tailandia', 'status' => 'Desactivado'],
                ['codigo' => 'TW', 'valor' => 'Taiwan, Provincia de China', 'status' => 'Desactivado'],
                ['codigo' => 'TZ', 'valor' => 'Tanzania, Republica Unida de', 'status' => 'Desactivado'],
                ['codigo' => 'TJ', 'valor' => 'Tayikistan', 'status' => 'Desactivado'],
                ['codigo' => '10', 'valor' => 'Territorio Britanico Oceano Indico', 'status' => 'Desactivado'],
                ['codigo' => 'TF', 'valor' => 'Territorios Australes Franceses', 'status' => 'Desactivado'],
                ['codigo' => 'TL', 'valor' => 'Timor Oriental', 'status' => 'Desactivado'],
                ['codigo' => 'TG', 'valor' => 'Togo', 'status' => 'Desactivado'],
                ['codigo' => 'TK', 'valor' => 'Tokelau', 'status' => 'Desactivado'],
                ['codigo' => 'TO', 'valor' => 'Tonga', 'status' => 'Desactivado'],
                ['codigo' => 'TT', 'valor' => 'Trinidad y Tobago', 'status' => 'Desactivado'],
                ['codigo' => 'TN', 'valor' => 'Tunez', 'status' => 'Desactivado'],
                ['codigo' => 'TM', 'valor' => 'Turkmenistan', 'status' => 'Desactivado'],
                ['codigo' => 'TR', 'valor' => 'Turquia', 'status' => 'Desactivado'],
                ['codigo' => 'TV', 'valor' => 'Tuvalu', 'status' => 'Desactivado'],
                ['codigo' => 'UA', 'valor' => 'Ucrania', 'status' => 'Desactivado'],
                ['codigo' => 'UG', 'valor' => 'Uganda', 'status' => 'Desactivado'],
                ['codigo' => 'UY', 'valor' => 'Uruguay', 'status' => 'Desactivado'],
                ['codigo' => 'UZ', 'valor' => 'Uzbekistan', 'status' => 'Desactivado'],
                ['codigo' => 'VU', 'valor' => 'Vanuatu', 'status' => 'Desactivado'],
                ['codigo' => 'VE', 'valor' => 'Venezuela', 'status' => 'Desactivado'],
                ['codigo' => 'VN', 'valor' => 'Vietnam', 'status' => 'Desactivado'],
                ['codigo' => 'VG', 'valor' => 'Islas Virgenes Britanicas', 'status' => 'Desactivado'],
                ['codigo' => 'WF', 'valor' => 'Wallis y Fortuna, Islas', 'status' => 'Desactivado'],
                ['codigo' => 'YE', 'valor' => 'Yemen', 'status' => 'Desactivado'],
                ['codigo' => 'ZM', 'valor' => 'Zambia', 'status' => 'Desactivado'],
                ['codigo' => 'ZW', 'valor' => 'Zimbabue', 'status' => 'Desactivado']
            ]

        ];

        DB::table('pais')->insert($pais);
    }
}
